version: '3.7'
services:
  db:
    image: postgres:12.6-alpine
    container_name: db
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
  server:
    build:
      context: ./blog-graphql-server
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: backend
    volumes:
      - ./blog-graphql-server:/work/backend
    env_file:
      - ./blog-graphql-server/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx-server:
    build:
      context: ./blog-graphql-server/nginx
      dockerfile: Dockerfile
    container_name: nginx-backend
    volumes:
      - static_volume:/usr/share/static
      - media_volume:/usr/share/media
    ports:
      - "8080:80"
    depends_on:
      - server
  client:
    build:
      context: ./blog-graphql-client
      dockerfile: Dockerfile.prod
    container_name: frontend
    volumes:
      - ./blog-graphql-client:/work/frontend
      - ./blog-graphql-client/nginx/:/etc/nginx/conf.d
      - /work/frontend/node_modules
    ports:
      - "3000:3000"
volumes:
  postgres_data_volume:
  static_volume:
  media_volume:
