version: '3.7'
services:
  server:
    build:
      context: ./blog-graphql-server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: backend
    volumes:
      - ./blog-graphql-server:/work/backend
    env_file:
      - ./blog-graphql-server/.env
    ports:
      - "8000:8000"
  client:
    build:
      context: ./blog-graphql-client
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./blog-graphql-client:/work/frontend
      - /work/frontend/node_modules
    ports:
      - "3000:3000"
